"use client";
import {useEffect,useRef} from "react";
export function Core({state}:{state:"idle"|"listening"|"thinking"}){
 const canvas=useRef<HTMLCanvasElement>(null),current=useRef(state);
 useEffect(()=>{current.current=state;},[state]);
 useEffect(()=>{const element=canvas.current!,ctx=element.getContext("2d");if(!ctx)return;let frame=0,angle=0,width=0,height=0,last=0;const reduced=window.matchMedia("(prefers-reduced-motion: reduce)");const resize=new ResizeObserver(()=>{width=element.clientWidth;height=element.clientHeight;const dpr=Math.min(devicePixelRatio,2);element.width=width*dpr;element.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);});resize.observe(element);
 const points=Array.from({length:2600},(_,i)=>{const y=1-i/2599*2,r=Math.sqrt(1-y*y),phi=i*Math.PI*(3-Math.sqrt(5));return{x:Math.cos(phi)*r,y,z:Math.sin(phi)*r};});
 function draw(time:number){if(!ctx)return;const dt=Math.min(time-last,50);last=time;const active=current.current==="thinking";if(!reduced.matches)angle+=dt*(active?.00065:.00013);ctx.clearRect(0,0,width,height);const cx=width/2,cy=height/2,r=Math.min(width,height)*.315;const glow=ctx.createRadialGradient(cx,cy,r*.2,cx,cy,r*1.6);glow.addColorStop(0,active?"#164c574b":"#083e533b");glow.addColorStop(.6,"#0b66882d");glow.addColorStop(1,"#07101800");ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(cx,cy);ctx.rotate(-.3);for(let j=0;j<3;j++){ctx.beginPath();ctx.ellipse(0,0,r*(1.15+j*.10),r*(.35+j*.08),.25+j*.55,angle*.3+j,angle*.3+j+Math.PI*1.5);ctx.strokeStyle=j===0?"#72d6ec66":"#53839830";ctx.lineWidth=.7;ctx.stroke();}ctx.restore();for(const p of points){const x=p.x*Math.cos(angle)-p.z*Math.sin(angle),z=p.x*Math.sin(angle)+p.z*Math.cos(angle),y=p.y*.94-z*.34,depth=p.y*.34+z*.94,ripple=reduced.matches?1:1+Math.sin(p.y*9+angle*5)*(active?.055:.018),scale=3/(3-depth*.4);ctx.fillStyle=`rgba(${active?"154,231,244":"98,204,239"},${.18+(depth+1)*.36})`;ctx.beginPath();ctx.arc(cx+x*r*scale*ripple,cy+y*r*scale*ripple,.45+(depth+1)*.48,0,Math.PI*2);ctx.fill();}frame=requestAnimationFrame(draw);}frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);resize.disconnect();};},[]);
 return <canvas ref={canvas} className={`core-canvas ${state}`} role="img" aria-label={state==="thinking"?"AI-ядро обрабатывает сообщение":"AI-ядро готово к работе"}/>;
}
