"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUp, Plus, Activity, Sparkles } from "lucide-react";
import { Core } from "@/components/khasroy/core";
import { chat, type Message } from "@/lib/chat";
const welcome: Message = { id: "welcome", role: "assistant", content: "Все системы готовы. Я Хасрой — ваш персональный AI-ассистент. С чего начнём?" };
export default function Home() {
 const [messages,setMessages]=useState<Message[]>([welcome]); const [input,setInput]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [focused,setFocused]=useState(false); const bottom=useRef<HTMLDivElement>(null); const field=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth",block:"nearest"});},[messages,busy]);
 async function send(value=input){if(!value.trim()||busy)return;const next:Message[]=[...messages,{id:crypto.randomUUID(),role:"user",content:value.trim()}];setMessages(next);setInput("");setBusy(true);setError("");try{const content=await chat(next);setMessages([...next,{id:crypto.randomUUID(),role:"assistant",content}]);}catch{setError("Не удалось получить ответ. Попробуйте ещё раз.");}finally{setBusy(false);field.current?.focus();}}
 return <main><header className="topbar"><a href="/" className="brand"><span className="brand-symbol">Х</span><span>Хасрой<span className="version">v0.1</span></span></a><div className="online"><span/>Хасрой ONLINE</div><span className="header-meta">PERSONAL INTELLIGENCE</span></header>
 <section className="stage" aria-label="AI-ядро"><aside className="system"><div className="eyebrow"><Activity size={14}/> SYSTEM STATUS</div><dl><div><dt>Ядро</dt><dd>Активно</dd></div><div><dt>Режим</dt><dd>Локальный</dd></div><div><dt>AI-модель</dt><dd className="muted">Не подключена</dd></div></dl><div className="signal">{Array.from({length:24},(_,i)=><i key={i}/>)}</div><p>ДЕМО-СЕССИЯ / 001</p></aside><div className="core-wrap"><Core state={busy?"thinking":focused?"listening":"idle"}/><span className="core-coordinate coord-left">NEURAL CORE<br/>Х — 01</span><span className="core-coordinate coord-right">{busy?"PROCESSING":"STANDBY"}<br/>● ACTIVE</span></div><div className="core-caption"><span className="eyebrow">{busy?"ОБРАБАТЫВАЮ СООБЩЕНИЕ":focused?"ВНИМАНИЕ НА ВАС":"НА СВЯЗИ. ГОТОВ К РАБОТЕ."}</span><h1>Мысль. Диалог. Возможности.</h1><p>Ваше пространство для больших идей.</p></div><div className="stage-index">01 / INTELLIGENCE CORE</div></section>
 <section className="chat" aria-label="Чат с «Хасрой»"><div className="chat-heading"><div><span className="chat-indicator"/>Диалог <span className="demo">DEMO</span></div><button className="new-chat" disabled={busy} onClick={()=>{setMessages([welcome]);setInput("");setError("");field.current?.focus();}}><Plus size={16}/>Новый диалог</button></div><div className="messages" role="log" aria-live="polite" aria-label="История сообщений">{messages.map(m=><article className={`message ${m.role}`} key={m.id}><div className="avatar">{m.role==="assistant"?<Sparkles size={16}/>:"ВЫ"}</div><div><div className="message-label">{m.role==="assistant"?"Хасрой":"ВЫ"}{m.role==="assistant"&&<span>Локальный ответ</span>}</div><p>{m.content}</p></div></article>)}{busy&&<div className="typing" role="status"><i/><i/><i/><span>Хасрой формирует демо-ответ</span></div>}<div ref={bottom}/></div>{messages.length===1&&!busy&&<div className="suggestions">{["Что ты умеешь?","Помоги с идеей","Проверь статус системы"].map(t=><button key={t} onClick={()=>send(t)}>{t}<span>↗</span></button>)}</div>}{error&&<p role="alert" className="error">{error}</p>}<form className="composer" onSubmit={e=>{e.preventDefault();send();}}><textarea ref={field} value={input} maxLength={4000} rows={1} placeholder="Напишите «Хасрой»…" aria-label="Сообщение для «Хасрой»" onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><button type="submit" className="send" aria-label="Отправить сообщение" disabled={!input.trim()||busy}><ArrowUp size={21}/></button></form><div className="chat-footer"><span>Демо-режим · Ответы без подключения к AI</span><span>Enter — отправить ↵</span></div></section><footer className="page-footer"><span>Хасрой LAB / INITIAL RELEASE</span><span>СОЗДАН ДЛЯ ВАШИХ ИДЕЙ</span></footer></main>;
}
